# Generated by Django 4.2.3 on 2023-07-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_remove_alumnos_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('apellido', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('consulta', models.CharField(max_length=400)),
            ],
        ),
    ]
